name: eeg_consciousness
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - ipykernel
  - scikit-learn
  - pip
  - pip:
    - mne
    - mne-bids
    - pyedflib
    - pywavelets
    - tqdm
    - plotly
    - kaleido 